### ISSUE TITLE
isim commnet

### ISSUE THREAD

**Issue by VB10** [Sedatdynn/FitnessApp#1]
https://github.com/Sedatdynn/FitnessApp/blob/b05b8365538549f82decc947e3eb8ac70fff1d2e/fitness_app/lib/product/widget/appBar/custom_app_bar.dart#L4

custom appbar ise dosya ismi file ismide sınıf ismideö lye olmalı birde comment vs atarak açıklamak lazım nedir bu diye

**Comment by Sedatdynn** [comment]
Projenin kodlarini tekrar kontrol ederek gerekli yerlere aciklamalar ekledim, tesekkurler Hocam.
