### ISSUE TITLE
genel

### ISSUE THREAD

**Issue by VB10** [Sedatdynn/FitnessApp#2]
https://github.com/Sedatdynn/FitnessApp/blob/b05b8365538549f82decc947e3eb8ac70fff1d2e/fitness_app/lib/feature/home/bmi/widget/bmi_widget.dart#L18

cok fazla context.watch olmus bu boyle olmak yerine lisener selector kullanmak gerekir
cok fazla iç içe componentler ve çağrılar olmus
widgetler parçalanmamış widget olarak
localizasyion etc.

**Comment by Sedatdynn** [comment]
https://github.com/Sedatdynn/FitnessApp/blob/9768d86940451eef3f46b66417eb3b37e56adf5b/fitness_app/lib/feature/home/bmi/widget/bmi_widget.dart#L8C12-L8C24
Hocam belirtmis oldugunuz gibi watch lari kaldirip BlocSelector kullanarak state uzerinden okuma yaptim. Widget'lari ayirma islemlerini de belirtmis oldugunuz dosyada yaptim ama genel olarak projeyi gozden gecirecegim.
Tesekkurler geri dönüşünüz için.

**Comment by Sedatdynn** [comment]
Hocam belirtmis oldugunuz gibi hem genel olarak bloc kullanimlarini hem ic ice yapilari gozden gecirdim.Ayrica projeye easy localization paketi ile coklu dil destegi entegre ettim.Tekrardan tesekkurler.
