### ISSUE TITLE
genel

### ISSUE THREAD

**Issue by VB10** [Sedatdynn/FitnessApp#7]
https://github.com/Sedatdynn/FitnessApp/blob/353959851c193430de92faa54c5d7d5ca858da75/fitness_app/lib/feature/home/diet/model/foods_model.dart#L40

repoyu sevdim temiz bir kaç nokta gözüme çarpı
- misal bu modelde türkçe isim vermemek lazım json veriable türkçe bile olsa ing verip name prop türkçe olanı atabilrisn
- misal bu kodu yaz sorun yok ama buna tood at bu kodu daha iyi nasıl yaparıdm diye forecelemarlı kontrol etmen lazım vs
- cubit sınıflarında olan businessleir daha sakin daha parçalı yazaibliriz

  state.foods[index1].icerik![index2] =
        state.foods[index1].icerik![index2].copyWith(kontrol: value);

eline sağlık genel olarakk akar

**Comment by Sedatdynn** [comment]
Çok teşekkürler Hocam, belirtmiş olduğunuz yerleri gözden geçirecegim.

**Comment by Sedatdynn** [comment]
Hocam soylemis oldugunuz yerleri tekrar gozden gecirip duzenlemeleri tamamladim, incelemeniz icin tesekkurler.
